/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.biblioteca.view;

import com.mycompany.biblioteca.controller.LoanController;
import com.mycompany.biblioteca.model.Book;
import com.mycompany.biblioteca.view.resources.TableModelLibro;
import com.mycompany.biblioteca.view.resources.TableModelListenerLibro;
import com.mycompany.biblioteca.view.resources.TableModelListenerSocio;
import com.mycompany.biblioteca.view.resources.ValidadorDeCampos;
import java.awt.Color;

/**
 *
 * @author ARIEL
 */
public class JPanel_ProcesarPrestamo_paso2 extends javax.swing.JPanel {

    //Validado de campos
    ValidadorDeCampos validadorDeCampos;
    
    //variables de tabla
    private final TableModelLibro tableModelLibro;

    private Book libroSeleccionado;

    LoanController controlador;
    private JPanelMenu panelMenu;

    /**
     * Creates new form JPanel_ProcesarPrestamo_paso1
     */
    public JPanel_ProcesarPrestamo_paso2(JPanelMenu panelMenu, LoanController controladorP) {
        this.validadorDeCampos = new ValidadorDeCampos();
        
        this.tableModelLibro = new TableModelLibro();

        this.controlador = controladorP;
        this.panelMenu = panelMenu;

        initComponents();
        
         //agrega escuchadores de las tablas
        this.jtbl_libros.getSelectionModel().addListSelectionListener(new TableModelListenerLibro(this));
    
        validadarCampos();
        
        setupBotones();
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtf_titulo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_libros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jlbl_nombre = new javax.swing.JLabel();
        jbtn_cancelar = new javax.swing.JButton();
        jbtn_siguiente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlbl_isbn = new javax.swing.JLabel();
        jbtn_atras = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(814, 600));
        setMinimumSize(new java.awt.Dimension(814, 600));
        setPreferredSize(new java.awt.Dimension(814, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Titulo");

        jtf_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_titulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_tituloKeyReleased(evt);
            }
        });

        jtbl_libros.setModel(tableModelLibro);
        jScrollPane1.setViewportView(jtbl_libros);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jlbl_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_nombre.setText("jLabel4");

        jbtn_cancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_cancelar.setText("CANCELAR");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        jbtn_siguiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_siguiente.setText("SIGUIENTE");
        jbtn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_siguienteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ISBN");

        jlbl_isbn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_isbn.setText("jLabel9");

        jbtn_atras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtn_atras.setText("ATRAS");
        jbtn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jtf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_isbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jbtn_cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_siguiente)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlbl_isbn))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlbl_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cancelar)
                    .addComponent(jbtn_siguiente)
                    .addComponent(jbtn_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        this.panelMenu.bloquearBotones(true);
        this.panelMenu.limpiarPanelContenido();
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    private void jbtn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_siguienteActionPerformed
        
        if (this.libroSeleccionado != null) {
            this.controlador.getNewLoan().setBook(libroSeleccionado);
            JPanel_ProcesarPrestamo_paso3 panelPaso3 = new JPanel_ProcesarPrestamo_paso3(this.panelMenu, this.controlador);
            
            panelPaso3.setSize(814, 600);
            this.panelMenu.limpiarPanelContenido();
            this.panelMenu.getjPanel_contenido().add(panelPaso3);
            this.panelMenu.repaint();
            this.panelMenu.validate();           
            
        }else{
            System.out.println("selecciona un libro");
        }
        
    }//GEN-LAST:event_jbtn_siguienteActionPerformed

    private void jtf_tituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_tituloKeyReleased

        if (this.jtf_titulo.isEditable()) {
            //Actualizar el TableModel con la lista del controlador
            this.tableModelLibro.setBooks(this.controlador.findBookByTittle(this.jtf_titulo.getText()));

            //Refrescar el modelo en la tabla
            this.tableModelLibro.fireTableDataChanged();
        }
    }//GEN-LAST:event_jtf_tituloKeyReleased

    private void jbtn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_atrasActionPerformed
        
        JPanel_ProcesarPrestamo_paso1 panelPaso1 = new JPanel_ProcesarPrestamo_paso1(this.panelMenu, this.controlador);

        panelPaso1.setSize(814, 600);

        this.panelMenu.limpiarPanelContenido();

        this.panelMenu.getjPanel_contenido().add(panelPaso1);

        this.panelMenu.repaint();
        this.panelMenu.validate();        
       
    }//GEN-LAST:event_jbtn_atrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_atras;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JButton jbtn_siguiente;
    private javax.swing.JLabel jlbl_isbn;
    private javax.swing.JLabel jlbl_nombre;
    private javax.swing.JTable jtbl_libros;
    private javax.swing.JTextField jtf_titulo;
    // End of variables declaration//GEN-END:variables

    /**
     * Selecciona una fila de la tabla, devolviendo un objeto Persona
     */
    public void seleccionarLibro() {        //obtiene el indice de la fila seleccionada en la tabla de personas
        int filaSeleccionada = this.jtbl_libros.getSelectedRow();
        // si la fila esta seleccionada, seteamos la persona auxiliar, llamando al modelo de tabla
        if (filaSeleccionada >= 0) {
            this.libroSeleccionado = this.tableModelLibro.getBookIn(filaSeleccionada);
            this.jlbl_isbn.setText(this.libroSeleccionado.getIsbn());
            this.jlbl_nombre.setText(this.libroSeleccionado.getName());
        }
    }
    
    private void validadarCampos(){
        this.validadorDeCampos.validarSoloLetras(jtf_titulo);
        this.validadorDeCampos.LimitarCaracteres(jtf_titulo, 25);
    }
    
    private void setupBotones(){
        this.validadorDeCampos.habilitarBoton(true, jbtn_cancelar, new Color(176, 128, 118), Color.WHITE, Color.GRAY, Color.BLACK);
    }
}
