/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.biblioteca.view;

import com.mycompany.biblioteca.controller.LoanController;
import com.mycompany.biblioteca.model.Partner;
import com.mycompany.biblioteca.view.resources.TableModelListenerSocio;
import com.mycompany.biblioteca.view.resources.TableModelSocio;
import com.mycompany.biblioteca.view.resources.ValidadorDeCampos;
import java.awt.Color;

/**
 *
 * @author ARIEL
 */
public class JPanel_ProcesarPrestamo_paso1 extends javax.swing.JPanel {

    //Validado de campos
    ValidadorDeCampos validadorDeCampos;
    
    //variables de tabla
    private final TableModelSocio tableModelSocio;

    private Partner socioSeleccionado;

    LoanController controlador;
    private JPanelMenu panelMenu;

    /**
     * Creates new form JPanel_ProcesarPrestamo_paso1
     */
    public JPanel_ProcesarPrestamo_paso1(JPanelMenu panelMenu, LoanController controladorP) {
        
        this.validadorDeCampos = new ValidadorDeCampos();
        //JTable vacio
        this.tableModelSocio = new TableModelSocio();

        this.controlador = controladorP;
        this.panelMenu = panelMenu;
        initComponents();

        //agrega escuchadores de las tablas
        this.jtb_socios.getSelectionModel().addListSelectionListener(new TableModelListenerSocio(this));
    
        validadarCampos();
        
        setupBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtf_numeroSocio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_socios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbl_nombre = new javax.swing.JLabel();
        jlbl_apellido = new javax.swing.JLabel();
        jbtn_cancelar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbl_dni = new javax.swing.JLabel();
        jlbl_numeroSocio = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(814, 600));
        setMinimumSize(new java.awt.Dimension(814, 600));
        setPreferredSize(new java.awt.Dimension(814, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("N° Socio");

        jtf_numeroSocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtf_numeroSocio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtf_numeroSocioKeyReleased(evt);
            }
        });

        jtb_socios.setModel(tableModelSocio);
        jScrollPane1.setViewportView(jtb_socios);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Apellido");

        jlbl_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_nombre.setText("jLabel4");

        jlbl_apellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_apellido.setText("jLabel5");

        jbtn_cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbtn_cancelar.setText("CANCELAR");
        jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cancelarActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("SIGUIENTE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("DNI");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("N° Socio");

        jlbl_dni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_dni.setText("jLabel8");

        jlbl_numeroSocio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbl_numeroSocio.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jbtn_cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(jtf_numeroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbl_numeroSocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbl_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbl_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbl_dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_numeroSocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jlbl_numeroSocio))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlbl_nombre))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbl_apellido))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlbl_dni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cancelar)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed
        this.panelMenu.bloquearBotones(true);
        this.panelMenu.limpiarPanelContenido();
    }//GEN-LAST:event_jbtn_cancelarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (this.socioSeleccionado != null) {
            this.controlador.getNewLoan().setPartner(socioSeleccionado);
            JPanel_ProcesarPrestamo_paso2 panelPaso2 = new JPanel_ProcesarPrestamo_paso2(this.panelMenu, this.controlador);

            panelPaso2.setSize(814, 600);

            this.panelMenu.limpiarPanelContenido();

            this.panelMenu.getjPanel_contenido().add(panelPaso2);

            this.panelMenu.repaint();
            this.panelMenu.validate();
            
            
        }else{
            System.out.println("selecciona socio");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtf_numeroSocioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_numeroSocioKeyReleased
        if (this.jtf_numeroSocio.isEditable()) {
            //Actualizar el TableModel con la lista del controlador
            this.tableModelSocio.setPartners(this.controlador.findPartner(this.jtf_numeroSocio.getText()));

            //Refrescar el modelo en la tabla
            this.tableModelSocio.fireTableDataChanged();
        }
    }//GEN-LAST:event_jtf_numeroSocioKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_cancelar;
    private javax.swing.JLabel jlbl_apellido;
    private javax.swing.JLabel jlbl_dni;
    private javax.swing.JLabel jlbl_nombre;
    private javax.swing.JLabel jlbl_numeroSocio;
    private javax.swing.JTable jtb_socios;
    private javax.swing.JTextField jtf_numeroSocio;
    // End of variables declaration//GEN-END:variables

    /**
     * Selecciona una fila de la tabla, devolviendo un objeto Persona
     */
    public void seleccionarSocio() {
        //obtiene el indice de la fila seleccionada en la tabla de personas
        int filaSeleccionada = this.jtb_socios.getSelectedRow();
        // si la fila esta seleccionada, seteamos la persona auxiliar, llamando al modelo de tabla
        if (filaSeleccionada >= 0) {
            this.socioSeleccionado = this.tableModelSocio.getPartnerIn(filaSeleccionada);
            this.jlbl_numeroSocio.setText(this.socioSeleccionado.getPartnerNumber());
            this.jlbl_nombre.setText(this.socioSeleccionado.getFirstName());
            this.jlbl_apellido.setText(this.socioSeleccionado.getLastName());
            this.jlbl_dni.setText(this.socioSeleccionado.getDni());
        }
    }
    
    private void validadarCampos(){
        this.validadorDeCampos.validarSoloNumero(jtf_numeroSocio);
        this.validadorDeCampos.LimitarCaracteres(jtf_numeroSocio, 5);
    }
    
    private void setupBotones(){
        this.validadorDeCampos.habilitarBoton(true, jbtn_cancelar, new Color(176, 128, 118), Color.WHITE, Color.GRAY, Color.BLACK);
    }

}
